### ISSUE TITLE
geologic age

### ISSUE THREAD

**Issue by megbalk** [futres/template#11]
We don't currently have a field if there is just one geologic age (i.e., no min or max).

**Comment by lbrensk** [comment]
Because the chronometric age extension is for reporting ages from relative or absolute dating methods, the chances of having a single known year for a geologic age in this case is basically slim to none. If there is just a one geological time period for a specimen, then the existing Darwin Core geological context terms (https://dwc.tdwg.org/terms/#geologicalcontext) should be used to report that. Or if we want to accommodate verbatim strings that describe geologic ages, there is the verbatimChronometricAge term from the chronometric age extension (https://tools.gbif.org/dwca-validator/extension.do?id=http://zooarchnet.org/dwc/terms/ChronometricAge).

**Comment by jdeck88** [comment]
Here is the set of geologicalContext and chronometric age terms in the GEOME FUTRES team:
![image](https://user-images.githubusercontent.com/1154501/70060281-141e5a80-1597-11ea-9825-4661571aa9ba.png)
It does not include all Darwin Core terms, see terms starting at: https://dwc.tdwg.org/terms/#dwc:geologicalContextID

This issue would be good to bring up for discussion at Gainesville meeting in two weeks.

**Comment by megbalk** [comment]
I'll add it to the agenda.

**Comment by megbalk** [comment]
keep lithostratigraphicTerms or report ChronometricAge
