### ISSUE TITLE
dynamicProperties

### ISSUE THREAD

**Issue by megbalk** [futres/template#27]
possibly for data that hasn't been parsed or extra data

**Comment by jdeck88** [comment]
We discussed on call yesterday to use the DwC reccomendations for dynamicProperties.  This field would need to be added to GEOME.  Essentially, we take in what user's provide (or what the pre-processor provides), preferably as JSON key/value pairs.  Still to decide is if we enforce JSON key/value pairs on the GEOME side or let anybody provide whatever content they want (which is really the direction of darwin core).

**Comment by jdeck88** [comment]
From the Excel Sheet Conversation/Update that Kitty sent there is a comment (under response 3 from kitty) that says: 
"decision was made not to accept dynamicProperties - instead that information should come already parsed out (e.g. the "chronometricAge extension" and "measurementOrFact extension" sets which would otherwise be also packaged in the dynamicProperties should be sent in the separate terms) and if not parsed out, it will not be accepted by FuTRES".   

This conflicts with release1.0.5 of the template and my recall of that conversation.  My recollection was that we would provide dynamicProperties as an option but not necessarily parse the contents downstream.. That is, we wouldn't suggest putting any essential content in this field, but to provide it as a way for inserting anything else the user may want to say about their data beyond what we've discussed.

**Comment by megbalk** [comment]
My understanding is that the workflow was: Template w dynamicProperties → verified through GEOME → flags that dynamicproperties has chronometric ext → use script to parse out → everything else ignored incl. Provenience since users need to do it themselves

**Comment by ramonawalls** [comment]
Yes, my memory agrees with @megbalk, HOWEVER, for metadata for which a DwC extension exists (e.g., chronometric extension), we WILL ask users to provide the metadata already parsed into columns rather than as dynamic properties. If they already have it in dynamic properties and want to keep it there too, no harm in that.

**Comment by megbalk** [comment]
if chronometric ext in dynamic properties, then flag it and push it back to the user to parse out themselves.
Anything else, we'll keep in dynamic properties but ignore it.

**Comment by megbalk** [comment]
if have zooarchaeological data, we'll ask the user to map it

**Comment by megbalk** [comment]
Flag will just say that there is data in dynamicProperties, not what specifically is in the field
