### ISSUE TITLE
skeletalElementCondition

### ISSUE THREAD

**Issue by megbalk** [futres/template#33]
to describe if the bone or specimen is broken and measurement is an estima
perhaps this gos into samplingProtocolte

**Comment by jdeck88** [comment]
From discussion yesterday, we discussed adding a new term: skeletalElementCondition
Can someone propose a coherent definition?  Is there a community standard term for this anywhere @ramonawalls ?

**Comment by ramonawalls** [comment]
@emerykf do you have a definition for skeletal element condition we can site? 

Kitty - you should be able to respond to this question just by answering email.

**Comment by emerykf** [comment]
I don't have one myself, but I bet Open Context does. Would this help? https://opencontext.org/vocabularies/oc-general/cat-modification?

We might also see if some of the paleo database folks have definitions to cite since they will also use this terminology I'm assuming.


________________________________________________________

Dr. Kitty F. Emery

Associate Curator, Environmental Archaeology

Florida Museum of Natural History

Dickinson Hall, 1659 Museum Road

University of Florida

Gainesville, FL 32611



352-273-1919 kemery@flmnh.ufl.edu<mailto:kemery@flmnh.ufl.edu>

www.floridamuseum.ufl.edu/envarch<http://www.flmnh.ufl.edu/envarch>

________________________________

**Comment by megbalk** [comment]
duplicate of #36

**Comment by megbalk** [comment]
Condition is different from Portion: e.g., if element is treated, glued, how they preserved it, if it was burned
