### ISSUE TITLE
find correct URIs for pco terms

### ISSUE THREAD

**Issue by jdeck88** [futres/template#7]
We need to insert the correct URI to insert in the template in the URI column (these are just place-holders):

pco:organismID
pco:collectionOfOrganismID

These will be modeled as data properties and not object properties.
@ramonawalls can help find these

**Comment by ramonawalls** [comment]
@jdeck88 @megbalk  Actually, the PCO terms are not correct here, because they are for the classes. We would want to create instance of these classes, but in the template, people need a space to fill in a pre-existing identifier for that instance. I am not aware of any data property for those fields, so we should just use an URN. Then the PCO term IRIs will go in the entity alias column (which I am finally thinking deeply about).
